# config/config.yaml
data:
  train_data_path: "data/train.csv"
  test_data_path: "data/test.csv"
  target_column: "target"

model:
  type: "RandomForest"
  n_estimators: 100
  max_depth: 10

logging:
  level: "INFO"
